Add :key to techs in v-for
FountainJS/generator-fountain-vue pull request #16
Opened 2017-03-14 03:42 UTC by atomantic

fixes issue:

```
WARNING in ./~/vue-loader/lib/template-compiler.js?{"id":"data-v-30277f8a"}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/app/techs/Techs.vue
<tech v-for="tech in techs">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
 @ ./src/app/techs/Techs.vue 5:2-178
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app/Main.vue
 @ ./src/app/Main.vue
 @ ./src/index.js
```

2017-07-14 20:39 UTC, FossPrime requested changes
one slight change

2017-07-14 20:39 UTC, rayfoss commented on generators/techs/templates/src/app/techs/Techs.vue
> +      <tech v-for="tech in techs" :tech="tech" :key="item.key"></tech>
use tech.key instead, item.key fails to load for me, though it does get rid of the error.

2017-07-15 13:46 UTC, atomantic commented
squashed in.

2017-07-15 14:10 UTC, FossPrime approved these changes
Works!

2026-03-02 19:19 UTC, closed without merging